before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: "{{ .ProjectName }}"
dockers:
  - image_templates:
      - "justcompile/cloudflare-dns-updater:{{ .Tag }}"
      - "justcompile/cloudflare-dns-updater:v{{ .Major }}"
      - "justcompile/cloudflare-dns-updater:v{{ .Major }}.{{ .Minor }}"
      - "justcompile/cloudflare-dns-updater:latest"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
